from pathlib import Path

MAX_INPUT_LENGTH = 500
MAX_CHAT_LENGTH = 500
MAX_AMOUNT = 10_000_000_000
MAX_TRANSACTIONS_PER_REQUEST = 50
MAX_TOTAL_TRANSACTIONS = 5000
RATE_LIMIT_SECONDS = 3

ASSETS_DIR = Path(__file__).resolve().parent / "assets"
FAVICON_PATH = ASSETS_DIR / "favicon.png"
